apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-pvc
  namespace: database
  annotations:
    recurring-job.longhorn.io/database-backups: "enabled"
spec:
  storageClassName: longhorn-custom
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi