---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: opensearch-secret
  namespace: database
spec:
  encryptedData:
    OPENSEARCH_PASSWORD: AgC5kwonfao2bWcKzVtQqAZ2lBV8SfAT6Y1GMwc5H9y3IZAqgcle4DzSyK4YCQpHB+9x1irpsjL3UW15CfFPrNaSsWAWRLIqM9zWFK3t/3cBbQRs7gO5zffp8shzGej19yidBugjXNSf4uMfet3Kb10cBR2pI2y/Nxk9cFuIgHeRN0sKe3cRl0kz5NTZSAvm0BSEeG85RGZ10ZxkaeJxcekpINKH4TETQmVnoJg7sVcBdI+CaJVD28/exizOGaw0KwCiru07yjkHrGWW9Y7rP+tarCMsTwcJDo7542QUVchPej/KetGnowX3giIqj9Yg7qf+0DepaR+n+jV5/RogYFeFi7BNpHa/oiDnZ9O9yRZ6gChqSTt+9IY2E27SJmcBLseQ3o3CSS7XM1moey34y6RGoxsLm/vCzySNMDfU5TSfnZDA3v6DIOzmbF1LjuFmzCdJi1Teps0Zfe9f6n+W33ejJ5wc5MjgFXi3+nt+OZ8WJ44msURaObCiCuxMK4gLU90ap7zYLo2UjvKVPNLgmVSg1q/Red3jHGUaz6eN1v2iq4ytYSAkOrOsc7n4K4ZilXLeOd+WZkoMm6f2dXl+8XNnebhwsfHQmrBvtR0yDfzABt8XmW7sa5cZnliTLjqXqFQEX2mrsgNK2zRmDH6c6suve46xM+ATQlq6EHlIvBRyx0/gsC3tc3I01kmr0VYUJh7odYqgdBe+V5k=
  template:
    metadata:
      name: opensearch-secret
      namespace: database
    type: Opaque
