apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-job.yaml
  - redis-job.yaml
  - neo4j-job.yaml
  - opensearch-job.yaml

# в зависимости от того, как будут ставиться бдшки, надо менять скрипты