apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: map-operator-hpa
  namespace: ism-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: map-operator
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70