---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aws-secrets
  namespace: ism-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBpBYNYNqS8lbazGI/OymcXbradTucM5+0NwyG6neVie+QW1IO9+FYwbhuZC+CrgV4sgyAtR+jdkIShQwnbLZfPrBq8rGZGQwikjyB+CffL8ipTsJaJ5KBCs14RJedwC8KfxHwKNV0ozvsfTn9oFmDp9ULQBa6CW19z6fccIn8d+NgikfHG6E1Db+9qmUUog0iyMRN4xREN3MQPHm2v4Abi/12+dNgfzqbydBTYYIq/YIBww/xJ5rub/zkFtFwn4LLMqYD2tL5R7zpC8NKyDhh1hFEVsCKCo+PyfLRp1r5yXIawICSdcxw1v2RNW6/s4gvkUO3eKcqV0JHsluXm5svoBQMcGb+R1+nOE+iAELr3bnt/vNXWVGdftRi+GCqdz4ftrjw5IVw99r8hGI2h8JlXA1em9k6yIqlfdMIOuOGs6wq0i+nTArLgVe2ACDzftpYUF9VF8CtRAJ8XDyc2aIeKv1cmy4X1cM14O6F/z7c1H907s9mNs7mBlYV3/ps4TGux/cbULcHNTW/IGzr1Klg4SGrkkjdR23yC4isbNGDM2I4wR6j8djINJBRSFzIMP4FzZNidF4Dsv3apxpbmUoUbxS8UH9knY5jD/K/J54x0hDGK/Vf0G0aRLImeGl2mAbTBF3iGd0Xifzx9tGolocztBARp8rZJ/TkuqxVNzeDeTs4pFFo54D4wS7bfTzPlfglSiuix8SAAMqA=
    AWS_SECRET_ACCESS_KEY: AgAr0vq/3XAMkYS3ncDPjxN8u1NUEqeig2nM4Gtg9XX5QghbN0zmq9Rrm5Z3Wohymw81Alj8JU9XR2qyb6j1m8pxzqgWzQMHZhoqXVl5uS63LfXM5AaXzUZFH2PlhGNxDQ/U5cmwuvP16fmnnvnWqsK8jSp0Hqpsa4oM2LfK7sEPsaE70jzMDU/Y1+5Tbi+eYXgUFigxdqbrKw3BQ6axRBalUSmWKQDjzPHMCXo/kwIH0u5iCQD6rqWeaHHKEbdhKZhonwltSs+AwmnAdZ9etE1UU3RhrieEQBsEnfaUZ2IL6S66mHjIo+KSJgQxtbuTpYTL1CcuU/qzUAGgOUeKE2dnoG4/ztzTc4dy3IToOft0kYOXvGiZqtS4yKwNRwrKL+0xhYTfkMf+tfgSrUBokOhCl2Wuou0BOrZ2frg1/Ll/vOMHvQw/Bvs+v/A+adxYfaQGM2m1hg5mjVyzQhaZZphePXZM91xJtWCyHW04Pp91aTymf59laAn4CQkuVAYiV/yvlOn3UbErTUd+13t23PYe3K4FCqp3bM8z3ImKOyjwL2ZgOGdiA2sGk7u7gjvfE61FPHj6VraRiH+JJrh967ejj3f0idR1MATYpWhNeI2Np/aJntrBcyntFgo6Tdhzlf9Yx4JTkubXuzdElsSyjT9QswTezcCV8ljE0S4/UL2cVtBoPHMUfn7MjWeUWispXD7Y/neWY/YRb2k=
  template:
    metadata:
      name: aws-secrets
      namespace: ism-system
    type: Opaque
