apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: ism-system
data:
  POSTGRES_HOST: postgres.database.svc.cluster.local
  POSTGRES_PORT: 5432
  AUTH_DB: ism_auth
  DB_USERNAME: ism_admin
  AUTH_SERVICE_SCHEMA: auth
  JWT_EXPIRATION: 86400000
  JWT_REFRESH_EXPIRATION: 604800000
  LOGGING_LEVEL_AUTH: INFO
  SPRING_SECURITY_LEVEL: WARN