---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-secrets
  namespace: ism-system
spec:
  encryptedData:
    DB_PASSWORD: AgBnQktNcm55sBuhZ75THggyKp41oI5venJoHVFKGekZBUdjiPdqLfIBdK0a52E/RwQncpgrnvCNJF9tEzEqbwgCxdOTY3aONhZ0Df/nnv/BkfaOUXwLpDQ/iWLrM4YBC4qLz6EwKbMweQ4jXW8aGTguh/6rx5MrvRbepf7U8B5CCqBvUkz6KVdET+KzUpqStYyVPiFvNJ/BN6SbipnOLKD9rkdpfYr8kltC2Qo4kwNzA5mmk9UWlGCjNKYfIs7Y6PESU5K/oY1MkqG59g86xHTmWEoHWpBvCviZ/cElP0zUOMgU/s10J4N9K0ybk43jEZOP6tAEB0vbEYJVJEMVnHJs1BjMd/WbWNlg6M9D8N2n1hkII6yq2gkiT/reqrNmj+bmtknI/SkDuOglCK9MemXErIE4qgpA6ygffDmHHcu1geNUmFiuI08p1wSmjwCKJw1IRPpH/28IxjvGzR6SRmILGZt+yeinjZSLx24Hg6kySHEwnAPEs8JASDJscWMRDSnQKZGuecqXMwCXhXLxrEH5YkRmb9DARVNf8O7rnUvL2x7TeD3LMX+ElLmCiDUBapTTxmyAOfLr4EQr4XyDz76vWpJOcaK+gpLBPZOcaZPVFdax7HCD3GbJNH7kdKX7Jw0MmoRfuyrgika/O2PJu6Gs3TU1jo3dtuXT6ntUQL0XdOvBmWr2OgvgrPETxWn6mz1aFiD+cJsyElo=
    JWT_SECRET: AgALM+pJdTUyAwbkhz1y5e09DqgJARiGnob6OXmJ0n1g9rqlRnegcB+b41EwN5t5uTQ4YaX+M0sexhSo3kCIQFffsnm8rPAuiNjWMyyqEdZ7AwkaEaStGO3xbsHYUy3i/UzWnF2go+akQqSgr4RRi+JKThcBA4WZPEe5rgdf0PfsKtAJl27UcS8iKNH1ZFkdYe/vwJbZJA8EyOQ38DVtIMN1YyzinOFPinc/7aoObvzZJ/VvcX/1XO7fIAO7wDmVCvuifBixirQwcLkN7M2RX0FqeoiMieXSw4jg+4itcZgAJ9nIb55RfyYBflnxQyBHquSWqbpt6mF/0ze0MY79DGY7I08sWm9hL9Q+kb3MhSvSuJDcRBf/V9HNrlQZx6rR2hk3DCb4bCri0AqfDl6rzBkyBR1BLy4olBgZRZt5IeLNiwViuc2unKrKPsCmPCnJoFwOMCuIWcNnh6F+6AB1i4M1ENRLX4gnqQAEB2Gb/c6Vk4HL/gbX0kdmYR9BeQDP8PE+QiFerH53Rqj1VAbj4YyWukwWmHi9dx2g3Ylu5wVDB9JYwet+h8dcw+28t9Xhv1Uaxa30d6CodHeC0utHkDrsJPJq9HeXns2yDzjOb9IR3TTlMPFYKYjbfrhOASDP7VfD5xYc+HA+xOQAT32FNKPWBNpoPxok+sjUK65AAykmyTQw86krieRJTkwFuBj4RL+CVYBXdA7Zym3uqmETpUYeq5aY7d+GYwvEVDtNL0oqIIxRdBc=
  template:
    metadata:
      name: auth-secrets
      namespace: ism-system
    type: Opaque
