apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-sa
  namespace: database
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-sa
  namespace: database
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opensearch-sa
  namespace: database
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: neo4j-sa
  namespace: database
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: localstack-sa
  namespace: ism-mq
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: map-operator-sa
  namespace: ism-system
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rag-sa
  namespace: ism-rag
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sync-operator-sa
  namespace: ism-system
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-sa
  namespace: ism-system
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: map-router-sa
  namespace: ism-system
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-sa
  namespace: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-sa
  namespace: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cadvisor-sa
  namespace: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alloy-sa
  namespace: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tempo-sa
  namespace: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-sa
  namespace: monitoring

#  kubectl label namespace database pod-security.kubernetes.io/enforce=restricted --overwrite
#  kubectl label namespace monitoring pod-security.kubernetes.io/enforce=restricted --overwrite