---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: database
spec:
  encryptedData:
    REDIS_PASSWORD: AgCSom43MvP9JOKCaWZO74cgoEj9U0EiO2qKLixVv2cTcdqdsEVdLI5/ySchxNJXajDPbLwOZVp9ya0w8Ht8gQX7CH6q6zf7fjE3KfspnQmyGNF8ptOz0M8xvpR3a/BNSHDIweE34hVwK4D6wSTtxUJYtkoj5nRQF4iheH9AzghSjR23Nr7cBODrcfk5IN1iZeneGPwBCqEFdUfqY++uckGrBy7IeAjbWAl18OHgflzYqG0sXKzG580JKOBU0Jhu48s6U+3XCbcSKONqIYE0+XtAlzN0tXrpd9VQUwrR831muCpr6yoBLuE8j6dt5CrY0qo1d8F0AEVOk9nneWfDwxqOfR8N/iowyBfCZmhCpzMb4yiOfI2nFZClIlrN2EXiVY3E3UCecwt+A7JLft3PIMlRWiTNyWhgKCX8NPnzqhvcFbyYcrz+gIqaNVEwSv4P3B+XFCJ9bRsBRn6Rlvj7Y73m4dQDdFb4ehlq6N1XNGVz5kTph41JOnPVjbH525Nz7mkcTMrc1e4ElAAi1iqpfICMqbCDE9NKxeSrSsLAZUuNIfp/K9W5cjwmKke/muNoA1GTR0t9o17PrC0JMAwWXW+nCVA1tZh0Nr6pWCa8zxPlEaqMf+6wtB2ueG2P4Kqq8VSspuy/kuC7WauetInu2GTCZvFCLZOkASD22KW7qWfOPXAGVepUP+tzyunj6H3uo04UVhb7O+5037w=
  template:
    metadata:
      name: redis-secret
      namespace: database
    type: Opaque
