apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.function.secretName }}
  namespace: {{ .Values.function.namespace }}
spec:
  encryptedData:
    {{- range $key, $value := .Values.sealedSecrets }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  template:
    metadata:
      name: {{ .Values.function.secretName }}
      namespace: {{ .Values.function.namespace }}
    type: Opaque