apiVersion: v1
kind: ConfigMap
metadata:
  name: sync-operator-config
  namespace: ism-system
data:
  SQS_SYNC_URL: http://localstack.ism-mq.svc.cluster.local:4566/000000000000/SQS_SYNC
  QUEUE_NAME: SQS_SYNC
  CHECK_INTERVAL: 10s
  AWS_ENDPOINT_URL: http://localstack.ism-mq.svc.cluster.local:4566
  AWS_REGION: us-east-1