---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aws-secrets
  namespace: ism-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAPB0m63Q1Wl+s9GEBSScpjlOUBcVEohyjw1NlmJCtMQB/hgZ3ob0FozKS84w1UoxpqoF6xTCa1e486G9eJc08pxKhmV+yoIJo0Fpagd/Jw2nR4Sv/4w+lL/qvRZKrHl+ppW9QoMYLfMPrcu27OFdvmsWrupZ6PzUHxEcRanRxqSqljhahzVr/BimPufGZMhUuytzQYWyYhpA+j0xfQeECJFyV5xDeigd8xKffP4HbhZxBp+Ke17URCCEEe3dfHwF8oT9FAouH96qgHv854x3PddeeHZHsAKPI5jgeyzIyhv95wp70WOX/bbho+5Y9avk59dUcwEhEFlAyooC1hM3itrXjXcuAyYGpD/3rIhIKSBf5NuI/mKkQjkuxma5c0tvt9/ToCvBCdUOA1+WjR7UaXTc6ZHPuCgWxc/GRZgrBmYRs1pyOcdgdv5she4+uHKVcGjKK2GmmGd67+WRNuDb0qOSJk32OLXmAGnHGFcCEbfoZ3dA5nNaAXUQQu3rFbDZbuTu5SVWMOQxXy9nFfRTEzg2NYi5yUteN/fh3ZizmGbB06UBWrvcvdWxAyYmSs63KLNxDgIw/5DvOafPf9TR/durr0OxyCAphyAcVqCspdkw1GXB/TOHD1pihbk/lYBvCWur06X02OHkg4uQ6DhCi7TH0nEY+iTv+PoiHZa6Yrit+M+GDUY1wtmWLUzRGLVi8S2AWf
    AWS_SECRET_ACCESS_KEY: AgCTLFUAagOC9H7rfkenxOMBayiq13gjCr7Rjlt4GmZpfZRw7LoRXTk/DxyPp5pY+bZOQ90qd9TS5nm/0wuVuNPTU4IoRb3/tjb5rTE+EcnJw2uVsLWCp0sjBowEURhAw8dGUDLB4drzX+pWMHD4jPxyYYtKkW95ONGwT5G8KyC1CrzBTtj2UkyJp49B1OOO3VVgdUUg66z73OnYN4oSZNbicntz5zPAv9Z/yhEny5IIaMlhx1r/1s2fqwsR8aLOPw8gGPqJulLyHAu9BYLJbTZPnEf0C6UjEoulKnUqyR4LgnIliiXsB6eBxIYlyAiK7oni+/ewFjOPmOkJ7B23Ciq6943iT1BfHwUiifZrJcDujB0MtapQ8XxsjnFanX0/mRzvYkHJ8gl628hupw8qFe5wihJmW2r/oaCNcs5vkQ/07JKc2YqvV5pga3muDVQTuS6q2oiK9A+h19mV/Vrr+7ffA8F1Cuks3xn7VGgPemZDUvzKjF+/g7hyBPLbVVISS0XmmEwiiiRw9EvUNX8LZR0+OhFCliCbz7MN0hPwxJoJAQS0oKyrzyNoX19MjBBUNHwA0woPC11tsvTp09sxuSLdHCSfdg79YLUoZNS3buWHhlFbZ6qE7OEa1flTdA9Sr1PI2MP4U24Xb0DbHk90TG+ZmjkgL0d34LDIASDZ2iRujWYVRHJf+V+ZwpFoOPNhzbsTYy4m
  template:
    metadata:
      name: aws-secrets
      namespace: ism-system
    type: Opaque
