apiVersion: v1
kind: Service
metadata:
  name: sync-operator
  namespace: ism-system
  labels:
    app: sync-operator
spec:
  selector:
    app: sync-operator
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090