apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: ism-rag
spec:
  selector:
    app: ollama
  ports:
    - port: 11434
      targetPort: 11434
      name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-headless
  namespace: ism-rag
spec:
  clusterIP: None
  selector:
    app: ollama
  ports:
    - port: 11434
      targetPort: 11434