apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - default-deny.yaml
  - auth-service-np.yaml
  - postgres-np.yaml
  - redis-np.yaml
  - opensearch-np.yaml
  - neo4j-np.yaml
  - localstack-np.yaml
  - map-router-np.yaml
  - map-operator-np.yaml
  - sync-operator-np.yaml
  - rag-agent-np.yaml
  - ingress-allow.yaml
  - ingress-to-system.yaml

# helm repo add cilium https://helm.cilium.io/
# helm install cilium cilium/cilium --namespace kube-system