apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - default-deny.yaml
  - auth-service-np.yaml
  - postgres-np.yaml
  - redis-np.yaml
  - opensearch-np.yaml
  - neo4j-np.yaml
  - localstack-np.yaml
  - map-router-np.yaml
  - map-operator-np.yaml
  - sync-operator-np.yaml
  - rag-agent-np.yaml
  - ingress-allow.yaml
  - ingress-to-system.yaml
  - egress-to-world.yaml
  - longhorn-allow.yaml
  - longhorn-out.yaml
  - kpack-dns.yaml
  - watcher-dns.yaml

#  helm repo add cilium https://helm.cilium.io/
#  helm install cilium cilium/cilium \
#    --namespace kube-system \
#    --set egressGateway.enabled=true \
#    --set bpf.masquerade=true \
#    --set kubeProxyReplacement=true \
#    --set encryption.enabled=true \
#    --set encryption.type=wireguard \
#    --set ingressController.defaultSecretNamespace=kube-system \
#    --set ingressController.defaultSecretName=default-cert \
#    --set envoy.enabled=true \
#    --set ingressController.enabled=true \
#    --set ingressController.default=true \
#    --set ingressController.loadbalancerMode=shared \
#    --set envoy.enabled=true \
#    --set envoyConfig.enabled=true \
#    --set hubble.enabled=true \
#    --set hubble.ui.enabled=true \
#    --set hubble.relay.enabled=true \
#    --set hubble.metrics.enable='{dns,drop,tcp,flow,icmp,http}'
#    --set tetragon.enabled=true \
#    --set tetragon.operator.enabled=true