apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
  labels:
    {{- include "map-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.mapOperator.secrets.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.mapOperator.secrets.awsSecretAccessKey | quote }}