{{- if .Values.service.authService.sealedSecrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "auth-service.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    DB_PASSWORD: {{ .Values.service.authService.sealedSecrets.encryptedData.dbPassword }}
    JWT_SECRET: {{ .Values.service.authService.sealedSecrets.encryptedData.jwtSecret }}
  template:
    metadata:
      name: {{ include "auth-service.fullname" . }}-secrets
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}