apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullname" . }}-secrets
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.service.secrets.dbPassword | quote }}
  JWT_SECRET: {{ .Values.service.secrets.jwtSecret | quote }}