---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: database
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgClWHAcUAU1KT1tIORrJSqghFmvQuWpWhN2ZbkQ7X5JHCpOWCG2hx5yHZrYyzPr6VF3xfGXTkRldQu7OetaVrl4E74WfTDSzKad6YAT4kBYSMPhUjPvVUboBQDAeyHBXPTRxD/2xknfTYof+zhHf8daOm8LBRASM7laXpyjl8Gs/XIOi+lda/1UGiQ7kn3v+4ToFi2oHrXHuXb8+Mxl6kN0lMo1VazMuSFGJl0gFiIdRj/7R0d2lCtXlfy9K3cb5nZ7idUE/Qk2nEgHcvjMPokYcX+akNBG4BQ6Vzgme15Qe1XlG8Pn9pjNcGhMw/I7SUFkHfwfk5lm0CgmKxrOHjV81VyW4CFWeNk/0Sa5MswiQy0EIeBrXNPyy3Prx0KTidHoBhOrNgGVbytCu+kgUlnefAVrIdDIqIOMW8I23BDhECN4uttd90KG6zM6m0eqqlCNCBiLCqpgOnT6wlkDjLhvFWjmmzI7PlHe8wjAUkZSkmLfbF50deUF/nvG+0awQxe1RfTy7j/PMW3+raxnU9A5+nmXE8vaKFYVL4wJR+2J72M5osUEoE4PXltBvI7Z0RwwCOpY4BNoCIW1/TunzDjAmliXiiXXY/zsnHFcYim7t8ZTAzLj6rhxh3lXkv8/mhgkDPHczuvF0qoNS9yMlH3C+v2CTABba99UfUXZo+TgRkHMJV4XXTzOVCY/XC6ZW6BJbku+UkkT688=
    POSTGRES_USER: AgBJQrB6p5YYhyYOLLbsCihD6n75YajmHlolytjbIMWRkv4CCpfwLVwKufHAfZVMd+Sv6TLHiWkJKbYK9spNfu/BtDzip5VYzm2QSO0UQs7aMqvJ2X6F4E15fVPV8vLGJQBdUJMmp7dcS3TxTiS7eoQiEtJTpB58rWUKMZrOwnMSA8acjIwUGiakixYIeXl59S2ogYi9kw+nNPZiSWXepV0mZE7IPkyY7maEKXHaavnO0uGvO6w9Uc4dUspVLMxF1GEgWqPMBYGgyjUCq9HYyX4krhyYlfXPxVIFn8QXrK2wmmgVU5CD/PHomwneM5CFkm/AQNeSWoycjcZFspbcnH0H5jYwfvEK0d/elg2kNKMpdXIF69ajATdLpPCP6IupBvthknGu0qG1t4U3TVgBOnG/PPGMqDTlEFKR25Gudky8fGMKsSSwqUzDSnf93rZ5T6JtgzTViLvkgj0OpDr/OcLKRTmtALpQOi+Y7pKratVwN6wSqLf62Fie9m9tYS/sBe3c61oTF453mNwJgR8g5HZ8A8yjJEeFW3X9arJ9xej68oO13vxo2fZxQbhISoNTojHdFTJ0GoTKQxR/rh2BH03fpCZH0wBe1CVVed9FnGT0fho1+7m02JbsQ50DGpV8slyk6ExERUZfCKCcXC1ecmqoG1tDD9bkytSlg+Ve5Pa/e8qxipFazNg4KP2rcG1ZON/gF2pHF0ClwdQ=
  template:
    metadata:
      name: postgres-secret
      namespace: database
    type: Opaque
