apiVersion: v1
kind: Secret
metadata:
  name: router-secret
  namespace: ism-system
type: Opaque
stringData:
  REDIS_PASSWORD: CHANGE_ME
  AWS_ACCESS_KEY_ID: CHANGE_ME
  AWS_SECRET_ACCESS_KEY: CHANGE_ME
  JWT_SECRET: CHANGE_ME_SIZE_AT_LEAST_32