---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    GF_SECURITY_ADMIN_PASSWORD: AgAj+5+CPu423zsZhBB8F93DkQ0gaiMi+jtxpWce8W81f3pIwae2zfdRSAGyJmoPT4tCfMiRExXUpUsNKw1CFLPQDUCDt2v2/CJwS++xKXfCu+KJpa5ND2rHKmwB0ufi/fx5WrNEpc0aH7k1csbhUd6+QSr/HTVhgKzeaHbwWUJawjNqfO6QppVy3p1zV7E9GzeOAEbtQbCvcQvWtjspgQp9cxpsM0VfONxQFvo4GrBvmqn4dX7JXcea0wMfX4iB9mkVc/UL0I7qzmiYh+wLLhCKFlZBEjtPKc3iyd3KGPJ2xfiV1n8/vl0OiVEuFWPJqvrNtftxGbrzFcKtqCKjDsYRo6qkvfqfdWuRigp2JZ+7A+RcGlaCmUR4ZdIbQTgsW/hFeJDtcQrBKLHcgMVY59L6kDXYrLp3bBmDaPuqZP2kdWPw86fmDO1+L+C808mRwmbSgeHJ1MgpEhvUeqPqkTKf2y2MVmdjDPhzGEeK4EmZKPYmeOhUZfyKH17dYBmwrM8f8PkUewD0joAztg5sgAW1wFpWsiy5Tb0jHUCiRywS0bFiEqqXAjXfZ23SmlW49CWeqU9s+zcR2F5L6lk+TlCT4WQEk65Bwwzy4FOcbh/Jyn9bJU2KfmJOLoaWpl+94Hpw9CtAHi8wpEgoFEE+HzpRDhGtsWbf62y0JhpNws6XDxmpbWdOhQLVKgECB6GtG3N8fQ2UiNLX9Vk=
    GF_SECURITY_ADMIN_USER: AgBTzh2+Nb8lN9rwm2Mc0BNocu1syfOAxcMze5ad7cCCvE0tRDRntinYo2dhoFUbG7UzPTa8MaFtFtBUyzIr+aFFuxCAwYerDYW3yw9R38luHN3UriArU9YUVCxPv4afjc54ZAu61xGMbwPp7Jzkuqh8bEbnJlx19K7G1bhvSmmHvENdnaOxzKS6Qxqd5dQK5lLQhdEt0zPNIhz+BF5ENMwqK85O1nqKX3XXE2yTaDJ7alXkbB5fKG28HO5Hdojimu+oKApMJ0Cmrais0Irz4hJ8j0wtOmn7voAUnuVU9YKaHQCZ9Zu/Jt0vVgrVk85kIQ1p1s0m2KXKR2qY7rTnL/TCM7QuMgKAS8DpdU6N/jTX3614vu6WlrYAnkQr+R4cUp5+HDxIt9gDnxhOuu9t8eN5gOFrHUYM7KuwRnT2WuDU+EmGCSGQi9mpYwBKfFlvaaanaRo6WAUf0spiHtezdtvFFgQUhP/syHc6mEagT46Y7pUKf3CRs5NAFZHvsOCnxKgblGM0gvpqwosVpR0dkj8m4sYcH7YKfMQW2iRkOdgmBNh9LUtYoIORArcOGRj8cV7CYeI1s7FvjmhC9k/eO2nGS9d0TbrQB1jknWiydCcnHjWBg8OQHZW5EfTHNWvIB+xyJhB7aN6PUsu6GQ2si4479hutR2524Srw1aEYPZ7OjFCsahxMsXN13ZJCeCRuCf6pXq8+e2G8+0E=
  template:
    metadata:
      name: grafana-secret
      namespace: monitoring
    type: Opaque
