apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - no-privileged.yaml
  - no-latest-tag.yaml
  - require-resources.yaml
  - exception.yaml
  - no-host-path.yaml
  - validate-pdb.yaml
  - validate-hpa.yaml
  - require-pdb-hpa-consistency.yaml
  - no-shared-process-namespace.yaml
  - no-default-namespace.yaml
  - no-nodeport-services.yaml