apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localstack-pvc
  namespace: ism-mq
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi