apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac
  - namespace
  - network-policy
  - mq
  - jobs
  - ism-system
  - database
  - admission-policies
  - monitoring
  - storage

# helm repo add bitnami https://charts.bitnami.com/bitnami
# helm install sealed-secrets bitnami/sealed-secrets --namespace kube-system --set fullnameOverride=sealed-secrets