apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-pvc-data
  namespace: database
  annotations:
    recurring-job.longhorn.io/database-backups: "enabled"
spec:
  storageClassName: longhorn-custom
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-pvc-logs
  namespace: database
  annotations:
    recurring-job.longhorn.io/database-backups: "enabled"
spec:
  storageClassName: longhorn-custom
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-pvc-plugins
  namespace: database
  annotations:
    recurring-job.longhorn.io/database-backups: "enabled"
spec:
  storageClassName: longhorn-custom
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi