---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: neo4j-secret
  namespace: database
spec:
  encryptedData:
    NEO4J_AUTH: AgBRA6E1cw3ERa6z5kv6gul97kTTHzQZ2AwaB3pkevsG92LgcbX1uy/Zc6Rf+AGx2qve0NtONdgUvNo2Yy20VvvpNvvnYjzhH9dIds496Si9UdKQJNn7B8yjhphvh/BFeRb+5zno+ks3pFilgnWy3KTUJiuh3s/5az+GCq98Tt9G6PnD93t/fDEE4VPXQ9jOtUau9HMcPO7fYsJZmUBYWCvX7fwV8WoSDDFTkbAzFCwhVsYtExOjCTlgJP06xDOOnMG+uh27erLoM5RjJfACzm6PNiDOwbHY8ae6TXDtcPnGS+UlNBC/JQ8baH+HeGYSb17GDNOdzs4bhRj+gCawogAkmYkp2xQb4+KokzzS72Js2mn2+fV8TcvRdBVl+6iCoP5YB6R3QQjBi48Zo4wuTTRGsB1bLHUHjgE498I9Igy26/7ojcPz0QlnCTAEjQi7XdPlwFnrv7M3qDhVT2VP7J7/c9rvd+DV+tsOC1Lc8EVIC+Nu5elj3bY+3UT4GRYeO6hWOPSayGzpy1a29JYYOZsn13Q4q8cRkZFEEmIvCd60giD5V/NhU0mIXBCpDnaa0HnKGy332RCUfzaw9mfXjDpcZjYEUg4Z0JN47Wl5H9RphecuoN7xY5Kcc6Oq54FwMyfn+7Vj/sr3o6fu13c66yvbD1nE+YwTc9W2bxvhv+MDe4eqQW1gVVVlO7TdjOfk54IfztYKtsPXTVPM3eCBow==
  template:
    metadata:
      name: neo4j-secret
      namespace: database
    type: Opaque
