apiVersion: v1
kind: Service
metadata:
  name: {{ include "rag-agent.fullname" . }}-agent
  labels:
  {{- include "rag-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.agent.type }}
  selector:
    app: rag-agent
    {{- include "rag-agent.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.agent.ports | toYaml | nindent 2 }}
