apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rag-agent.fullname" . }}-secrets
  labels:
    {{- include "rag-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.agent.secrets.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.agent.secrets.awsSecretAccessKey | quote }}