apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ism-rag

resources:
  - configmap.yaml
  - deployment.yaml
  - hpa.yaml
  - pdb.yaml
  - pvc.yaml
  - service.yaml

generatorOptions:
  disableNameSuffixHash: true