apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-pvc
  namespace: ism-rag
  annotations:
    recurring-job.longhorn.io/rag-backups: "enabled"
spec:
  storageClassName: longhorn-custom
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi