apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-pvc
  namespace: ism-rag
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi