config:
  awsEndpointUrl: http://localstack.ism-mq.svc.cluster.local:4566
  awsRegion: us-east-1
  checkInterval: 10s
  queueName: SQS_SYNC
  sqsSyncUrl: http://localstack.ism-mq.svc.cluster.local:4566/000000000000/SQS_SYNC
kubernetesClusterDomain: cluster.local
pdb:
  minAvailable: 1
serviceAccount:
  create: true
  name: sync-operator-sa
  annotations: {}
  automount: false
syncOperator:
  secrets:
    awsAccessKeyId: test
    awsSecretAccessKey: test
  serviceAccount:
    create: true
    name: sync-operator-sa
    annotations: {}
    automount: false
  nodeSelector: {}
  operator:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
    image:
      repository: pyrodocker1/sync-operator
      tag: "0.1"
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
  replicas: 1
  tolerations: []
  topologySpreadConstraints: []
  type: ClusterIP
