apiVersion: v1
kind: Secret
metadata:
  namespace: openfaas-fn
  name: faas-m-secrets
type: Opaque
stringData:
  NEO4J_PASSWORD: test1234
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
  OPENSEARCH_PASSWORD: admin