apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: monitoring
  labels:
    app: tempo
spec:
  selector:
    app: tempo
  ports:
    - port: 3200
      targetPort: 3200
      name: http
    - port: 4317
      targetPort: 4317
      name: otlp-grpc
    - port: 4318
      targetPort: 4318
      name: otlp-http
    - port: 9096
      targetPort: 9096
      name: grpc
    - port: 14268
      targetPort: 14268
      name: jaeger
    - port: 9411
      targetPort: 9411
      name: zipkin
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: tempo-headless
  namespace: monitoring
spec:
  clusterIP: None
  selector:
    app: tempo
  ports:
    - port: 3200
      targetPort: 3200
      name: http
    - port: 4317
      targetPort: 4317
      name: otlp-grpc
    - port: 4318
      targetPort: 4318
      name: otlp-http
    - port: 9095
      targetPort: 9095
      name: grpc