apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: go-operator
  namespace: ism-system
spec:
  selector:
    matchLabels:
      app: go-operator
  endpoints:
    - port: metrics
      interval: 10s

#  helm repo add openfaas https://openfaas.github.io/faas-netes/
#  helm repo update
#
#  kubectl create namespace openfaas
#  kubectl create namespace openfaas-fn
#
#  helm upgrade openfaas --install openfaas/openfaas \
#  --namespace openfaas \
#  --set functionNamespace=openfaas-fn \
#  --set generateBasicAuth=true \
#  --set gateway.replicas=2 \
#  --set queueWorker.replicas=2
#
#  helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
#  helm repo update
#
#  helm install prometheus prometheus-community/kube-prometheus-stack \
#  --namespace monitoring \
#  --create-namespace \
#  --set grafana.enabled=false \
#  --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false