apiVersion: v1
kind: Service
metadata:
  name: {{ include "map-router.fullname" . }}-router
  labels:
  {{- include "map-router.labels" . | nindent 4 }}
spec:
  type: {{ .Values.router.type }}
  selector:
    app: map-router
    {{- include "map-router.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.router.ports | toYaml | nindent 2 }}
