{{- if .Values.router.secrets.sealedSecrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "map-router.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "map-router.labels" . | nindent 4 }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    REDIS_PASSWORD: {{ .Values.router.secrets.sealedSecrets.encryptedData.redisPassword }}
    AWS_ACCESS_KEY_ID: {{ .Values.router.secrets.sealedSecrets.encryptedData.awsAccessKeyId }}
    AWS_SECRET_ACCESS_KEY: {{ .Values.router.secrets.sealedSecrets.encryptedData.awsSecretAccessKey }}
    JWT_SECRET: {{ .Values.router.secrets.sealedSecrets.encryptedData.jwtSecret }}
  template:
    metadata:
      name: {{ include "map-router.fullname" . }}-secret
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}