apiVersion: v1
kind: Secret
metadata:
  name: {{- include "map-router.fullname" . | nindent 4 }}-secret
  labels:
    {{- include "map-router.labels" . | nindent 4 }}
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.router.secrets.redisPassword | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.router.secrets.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.router.secrets.awsSecretAccessKey | quote }}
  JWT_SECRET: {{ .Values.router.secrets.jwtSecret | quote }}
