apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sync-operator.fullname" . }}-config
  labels:
  {{- include "sync-operator.labels" . | nindent 4 }}
data:
  AWS_ENDPOINT_URL: {{ .Values.config.awsEndpointUrl | quote }}
  AWS_REGION: {{ .Values.config.awsRegion | quote }}
  CHECK_INTERVAL: {{ .Values.config.checkInterval | quote }}
  QUEUE_NAME: {{ .Values.config.queueName | quote }}
  SQS_SYNC_URL: {{ .Values.config.sqsSyncUrl | quote }}
