{{- if .Values.syncOperator.secrets.sealedSecrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "sync-operator.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sync-operator.labels" . | nindent 4 }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: {{ .Values.syncOperator.secrets.sealedSecrets.encryptedData.awsAccessKeyId }}
    AWS_SECRET_ACCESS_KEY: {{ .Values.syncOperator.secrets.sealedSecrets.encryptedData.awsSecretAccessKey }}
  template:
    metadata:
      name: {{ include "sync-operator.fullname" . }}-secrets
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}