apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sync-operator.fullname" . }}-secrets
  labels:
    {{- include "sync-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.syncOperator.secrets.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.syncOperator.secrets.awsSecretAccessKey | quote }}