apiVersion: v1
kind: Service
metadata:
  name: {{ include "sync-operator.fullname" . }}-sync-operator
  labels:
    app: sync-operator
  {{- include "sync-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.syncOperator.type }}
  selector:
    app: sync-operator
    {{- include "sync-operator.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.syncOperator.ports | toYaml | nindent 2 }}
